### ISSUE TITLE
Proper Creative Commons license for logos

### ISSUE THREAD

**Issue by jzaefferer** [jquery/brand.jquery.org#22]
When creating the Globalize page on Wikipedia, I used the Globalize logo from http://brand.jquery.org/logos/#proper-usage  I converted the EPS file to SVG and uploaded it: https://en.wikipedia.org/wiki/File:Globalize_logo.svg

The file is now [under review](https://en.wikipedia.org/wiki/Wikipedia:Files_for_discussion/2016_May_28#File:Globalize_logo.svg), since "No CC/PD release at source given.".

Since there is indeed no specific license at brand.jquery.org, I'm hoping that we can add a Creative Commons license. As far as I can tell, http://creativecommons.org/licenses/by-nc-nd/4.0/ would be the closest to the current text under "Proper Usage".

If someone feels like this is the wrong place for this discussion, please move it to a better place.

/cc @kborchers

**Comment by kborchers** [comment]
That logo is definitely not available under a CC license. There is currently a pending trademark application under review. All branding elements for jQuery Foundation projects fall under this trademark policy https://jquery.org/trademark-policy/ If you know of any other project logos that are listed on Wikipedia under an incorrect license, please let us know.

**Comment by jzaefferer** [comment]
At least that link needs to be on this site.

Besides that, does this look right to you? https://en.wikipedia.org/wiki/File:JQuery_logo.svg - if so, I'd just reuse the license templates there.

**Comment by kborchers** [comment]
I believe that looks right but I would like @stevenayr to confirm before replicating across any other logos/trademarks we have on Wikipedia.

I will update the brand site to reference the trademark policy as well. Thanks!

**Comment by StevenAyr** [comment]
That looks good to me. Makes clear the mark is protected by copyright and trademark, but provides appropriate justification for why use on wikipedia is a fair use (under both). I think the rationale and license info can both be used across Foundation marks.

**Comment by kborchers** [comment]
Great, thanks Steve! I have also added a link to the trademark policy from the logos page with some other clarifying updates in https://github.com/jquery/brand.jquery.org/commit/aa6f58b88ea94501dd83484ba3ffa12e4ddcff36 and published so this should be good to go. Please reopen if you have other questions/concerns on this topic.

**Comment by jzaefferer** [comment]
Okay, I've updated the license for the Globalize logo: https://en.wikipedia.org/wiki/File:Globalize_logo.svg - I left the notice for now, hopefully the editor who flagged it will also remove it.
